# Generated by Django 5.2 on 2025-04-02 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('Category_slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=100, verbose_name='Item Name')),
                ('Item_description', models.TextField(verbose_name='Item Description')),
                ('Item_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Item Price')),
                ('Item_quantity', models.IntegerField(verbose_name='Item Quantity')),
                ('Item_published', models.BooleanField(default=False, help_text='Is this item published?', verbose_name='Item Published')),
                ('Item_createdat', models.DateTimeField(auto_now_add=True, verbose_name='Item Created At')),
                ('Item_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('Item_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Item.category')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
