# Generated by Django 5.2 on 2025-04-03 00:39

import Item.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Item_img',
            field=models.ImageField(blank=True, null=True, upload_to=Item.models.custom_upload_to),
        ),
        migrations.AddField(
            model_name='item',
            name='Item_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_owner', to=settings.AUTH_USER_MODEL, verbose_name='Item Owner'),
        ),
    ]
