# Generated by Django 5.2 on 2025-04-03 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0003_alter_item_item_owner'),
        ('Market', '0002_transaction_transaction_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='items',
        ),
        migrations.AddField(
            model_name='transaction',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_item', to='Item.item'),
        ),
    ]
